### PR TITLE
Create_drum_machine

### PR DESCRIPTION
**Pull request by FarwaMuhibZada**
# build-drum-machine 🔁

## Description 📜

 Build a drum machine app that mimics the functionality of the reference drum machine provided here. The app should be designed using React, and it should fulfill the user stories listed in the freeCodeCamp curriculum.

## Features 🎉

- Play sounds by clicking on buttons or pressing corresponding keys on the keyboard.
- Display the name of the currently playing sound on the screen.
- Provide visual feedback (e.g., changing button colors) when sounds are played.
- Include a set of drum pads with different sound categories (e.g., Kick, Snare, Hi-Hat).
- Allow users to switch between different sound sets or banks.
- Ensure accessibility by supporting keyboard navigation and screen readers.

## Demo 📸
deployment link :(https://drum-machine-farwaamhubzada.netlify.app/)
Capture

### CODE REVIEW

**Comment by MasomRezaie** [comment]
@FarwaMuhibZada . Well done Farwa Jan. Your project is great. I reviewed your coding. it was great and did not have any error. i approved this project.

**Comment by FarwaMuhibZada** [comment]
> @FarwaMuhibZada . Well done Farwa Jan. Your project is great. I reviewed your coding. it was great and did not have any error. i approved this project.

@MasomRezaie thanks for  reviewing  and feedback .

**Comment by FarwaMuhibZada** [comment]
> # build-drum-machine 🔁
> ## Description 📜
> Build a drum machine app that mimics the functionality of the reference drum machine provided here. The app should be designed using React, and it should fulfill the user stories listed in the freeCodeCamp curriculum.
> 
> ## Features 🎉
> * Play sounds by clicking on buttons or pressing corresponding keys on the keyboard.
> * Display the name of the currently playing sound on the screen.
> * Provide visual feedback (e.g., changing button colors) when sounds are played.
> * Include a set of drum pads with different sound categories (e.g., Kick, Snare, Hi-Hat).
> * Allow users to switch between different sound sets or banks.
> * Ensure accessibility by supporting keyboard navigation and screen readers.
> 
> ## Demo 📸
> Capture

**Review by ahzamir — APPROVED** [review]
### Hi @FarwaMuhibZada 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF


 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Drum Machine project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
